In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/Processed/Global_Superstore_Clean.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Market          51290 non-null  str
 12  Region          51290 non-null  str
 13  Product ID      51290 non-null  str
 14  Category        51290 non-null  str
 15  Sub-Category    51290 non-null  str
 16  Product Name    51290 non-null  str
 17  Sales           51290 non-null  float64
 18  Quantity        51290 non-null  int64
 19  Discount        51290 non-null  float64
 20  Profit          51290 non-null  float64
 21  Shipping Cost   51290 non-null  float64
 22  Order Priority  51290 non-null  str
dtypes: float64(4), int64(2), str(17)
memory usage: 9.0 MB

In [4]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  datetime64[us]
 3   Ship Date       51290 non-null  datetime64[us]
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Market          51290 non-null  str
 12  Region          51290 non-null  str
 13  Product ID      51290 non-null  str
 14  Category        51290 non-null  str
 15  Sub-Category    51290 non-null  str
 16  Product Name    51290 non-null  str
 17  Sales           51290 non-null  float64
 18  Quantity        51290 non-null  int64
 19  Discount        51290 non-null  float64
 20  Profit          51290 non-null  float64
 21  Shipping Cost   51290 non-null  float64
 22  Order Priority  51290 non-null  str
dtypes: datetime64[us](2), float64(4), int64(2), str(15)
memory usage: 9.0 MB

In [8]:
customers = (
    df[
        ["Customer ID", "Customer Name", "Segment"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

customers.head()

  Customer ID     Customer Name      Segment
0    RH-19495       Rick Hansen     Consumer
1    JR-16210     Justin Ritter    Corporate
2    CR-12730      Craig Reiter     Consumer
3    KM-16375  Katherine Murray  Home Office
4     RH-9495       Rick Hansen     Consumer

In [37]:
customers["Customer ID"].nunique()
len(customers)

1590

In [28]:
products = (
    df[
        [
            "Product ID",
            "Product Name",
            "Category",
            "Sub-Category"
        ]
    ]
    .drop_duplicates(subset=["Product ID"])
    .reset_index(drop=True)
)

In [30]:
products["Product ID"].nunique()
len(products)

10292

In [27]:
duplicados = products[
    products["Product ID"].duplicated(keep=False)
].sort_values("Product ID")

duplicados.head(20)

,Product ID,Product Name,Category,Sub-Category
852,FUR-BO-10000087,"Dania Classic Bookcase, Mobile",Furniture,Bookcases
1967,FUR-BO-10000087,"Sauder Corner Shelving, Pine",Furniture,Bookcases
3933,FUR-BO-10000112,"Dania Corner Shelving, Pine",Furniture,Bookcases
627,FUR-BO-10000112,"Bush Birmingham Collection Bookcase, Dark Cherry",Furniture,Bookcases
3318,FUR-BO-10000268,"Bush Library with Doors, Pine",Furniture,Bookcases
2630,FUR-BO-10000268,"Ikea 3-Shelf Cabinet, Traditional",Furniture,Bookcases
4652,FUR-BO-10000668,"Ikea Corner Shelving, Traditional",Furniture,Bookcases
942,FUR-BO-10000668,"Sauder Classic Bookcase, Mobile",Furniture,Bookcases
3167,FUR-BO-10000728,"Dania Corner Shelving, Traditional",Furniture,Bookcases
467,FUR-BO-10000728,"Ikea Classic Bookcase, Mobile",Furniture,Bookcases
4423,FUR-BO-10000895,"Sauder Corner Shelving, Metal",Furniture,Bookcases
4304,FUR-BO-10000895,"Sauder Stackable Bookrack, Pine",Furniture,Bookcases
2610,FUR-BO-10001155,"Dania 3-Shelf Cabinet, Traditional",Furniture,Bookcases
3410,FUR-BO-10001155,"Ikea 3-Shelf Cabinet, Metal",Furniture,Bookcases
2548,FUR-BO-10001585,"Ikea Floating Shelf Set, Traditional",Furniture,Bookcases
2473,FUR-BO-10001585,"Sauder Floating Shelf Set, Mobile",Furniture,Bookcases
3779,FUR-BO-10001646,"Safco Corner Shelving, Metal",Furniture,Bookcases
1726,FUR-BO-10001646,"Safco Library with Doors, Pine",Furniture,Bookcases
4132,FUR-BO-10002204,"Dania Floating Shelf Set, Traditional",Furniture,Bookcases
2625,FUR-BO-10002204,"Bush Corner Shelving, Traditional",Furniture,Bookcases

In [12]:
orders = (
    df[
        [
            "Order ID",
            "Order Date",
            "Ship Date",
            "Ship Mode",
            "Order Priority"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

orders.head()

          Order ID Order Date  Ship Date     Ship Mode Order Priority
0   CA-2012-124891 2012-07-31 2012-07-31      Same Day       Critical
1    IN-2013-77878 2013-02-05 2013-02-07  Second Class       Critical
2    IN-2013-71249 2013-10-17 2013-10-18   First Class         Medium
3  ES-2013-1579342 2013-01-28 2013-01-30   First Class         Medium
4     SG-2013-4320 2013-11-05 2013-11-06      Same Day       Critical

In [35]:
orders["Order ID"].nunique
len(orders)

25754

In [15]:
locations = (
    df[
        [
            "Country",
            "State",
            "City",
            "Region",
            "Market"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

In [16]:
locations["Location ID"] = locations.index + 1

In [33]:
products["Product ID"].nunique()
len(products)

10292

In [18]:
order_details = df[
    [
        "Order ID",
        "Product ID",
        "Customer ID",
        "Sales",
        "Quantity",
        "Discount",
        "Profit",
        "Shipping Cost"
    ]
].copy()

In [19]:
order_details = df.merge(
    locations,
    on=[
        "Country",
        "State",
        "City",
        "Region",
        "Market"
    ],
    how="left"
)

In [20]:
order_details = order_details[
    [
        "Order ID",
        "Product ID",
        "Customer ID",
        "Location ID",
        "Sales",
        "Quantity",
        "Discount",
        "Profit",
        "Shipping Cost"
    ]
]

In [31]:
customers.to_csv("../data/Processed/customers.csv", index=False)
products.to_csv("../data/Processed/products.csv", index=False)
orders.to_csv("../data/Processed/orders.csv", index=False)
locations.to_csv("../data/Processed/locations.csv", index=False)
order_details.to_csv("../data/Processed/order_details.csv", index=False)